// SUT Campus Data matching Reference Mockups

export const SUT_BUILDINGS = [
  { id: 'bld-dorm-low', name: 'กลุ่มหอพักสุรนิเวศ (Suraniwet Dorms)', code: 'DORM', zone: 'Dormitory', lat: 14.8828, lng: 102.0235 },
  { id: 'bld-b1', name: 'อาคารเรียนรวม 1 (Lecture Hall 1)', code: 'B1', zone: 'Academic', lat: 14.8785, lng: 102.0192 },
  { id: 'bld-b2', name: 'อาคารเรียนรวม 2 (Lecture Hall 2)', code: 'B2', zone: 'Academic', lat: 14.8765, lng: 102.0223 },
  { id: 'bld-eng1', name: 'อาคารวิชาการ 1 (Academic 1)', code: 'ACAD1', zone: 'Academic', lat: 14.8752, lng: 102.0180 },
  { id: 'bld-eng2', name: 'อาคารวิชาการ 2 (Academic 2)', code: 'ACAD2', zone: 'Academic', lat: 14.8741, lng: 102.0170 },
  { id: 'bld-lib', name: 'อาคารบรรณสาร (Library)', code: 'LIB', zone: 'Central', lat: 14.8798, lng: 102.0178 },
  { id: 'bld-dorm-high', name: 'หอพักสุรนิเวศ 11-17', code: 'DORM-H', zone: 'Dormitory', lat: 14.8858, lng: 102.0215 },
];

export const SUT_CANTEENS = [
  {
    id: 'canteen-5',
    name: 'Kasalong Canteen',
    thaiName: 'โรงอาหารกาสะลองคำ',
    locationNote: 'Suraniwet Dorms, Gate 4',
    shortName: 'Kasalong Canteen',
    tagline: 'Popular canteen near student dormitories',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
    lat: 14.8835,
    lng: 102.0240,
    openHours: '06:00 - 21:00',
    baseQueueMinutes: 15,
    queueLevel: 'Medium',
    stalls: [
      {
        id: 'stall-noodle-house',
        canteenId: 'canteen-5',
        name: 'Noodle House',
        thaiName: 'เตี๋ยวเรือแสดทอง',
        category: 'Noodles',
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        waitMinutes: 10,
        rating: 4.8,
        isOpen: true,
        fastest: false,
        menus: [
          { id: 'm-nh-1', name: 'Boat Noodle with Stewed Pork', price: 45, prepTime: 5, desc: 'Rich spiced broth with tender braised pork and meatballs', popular: true },
          { id: 'm-nh-2', name: 'Tom Yum Noodle Soup', price: 45, prepTime: 5, desc: 'Zesty lime, crushed peanuts, and minced pork', popular: true },
          { id: 'm-nh-3', name: 'Crispy Wonton Boat Noodle', price: 50, prepTime: 6, desc: 'Extra crispy golden wontons with boat noodle soup' },
        ],
      },
      {
        id: 'stall-mamas-kitchen',
        canteenId: 'canteen-5',
        name: "Mama's Kitchen",
        thaiName: 'ครัวเจ๊พร อาหารตามสั่ง',
        category: 'Made-to-Order',
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80',
        waitMinutes: 5,
        rating: 4.5,
        isOpen: true,
        fastest: true, // "FASTEST" badge from mockup
        menus: [
          { id: 'm-mk-1', name: 'Holy Basil Crispy Pork with Fried Egg', price: 50, prepTime: 5, desc: 'Signature spicy stir-fried crispy pork with crispy fried egg', popular: true },
          { id: 'm-mk-2', name: 'Thai Style Fried Rice with Shrimp', price: 50, prepTime: 5, desc: 'Wok-tossed fragrant jasmine rice with fresh prawns', popular: true },
          { id: 'm-mk-3', name: 'Creamy Omelette on Rice', price: 45, prepTime: 4, desc: 'Soft creamy eggs over hot jasmine rice' },
        ],
      },
      {
        id: 'stall-fruit-bar',
        canteenId: 'canteen-5',
        name: 'Fruit Bar',
        thaiName: 'ฟรุ้ตบาร์ สมูทตี้สด',
        category: 'Beverages',
        imageUrl: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=800&q=80',
        waitMinutes: 2,
        rating: 4.9,
        isOpen: false,
        fastest: false,
        menus: [
          { id: 'm-fb-1', name: 'Fresh Mango Passion Smoothie', price: 35, prepTime: 2, desc: '100% natural ripe mango blended with passionfruit', popular: true },
          { id: 'm-fb-2', name: 'Dragonfruit Berry Booster', price: 40, prepTime: 2, desc: 'Antioxidant rich red dragonfruit and mixed berries', popular: true },
          { id: 'm-fb-3', name: 'Watermelon Cold Pressed Juice', price: 30, prepTime: 1, desc: 'Refreshing pure watermelon juice with mint' },
        ],
      },
    ],
  },
  {
    id: 'canteen-3',
    name: 'Krua Than Thao Canteen',
    thaiName: 'โรงอาหารครัวท่านท้าว',
    locationNote: 'Opposite SUT Transportation Center',
    shortName: 'Krua Than Thao',
    tagline: 'Central campus canteen with evening market',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    lat: 14.8812,
    lng: 102.0168,
    openHours: '06:30 - 20:00',
    baseQueueMinutes: 8,
    queueLevel: 'Low',
    stalls: [],
  },
  {
    id: 'canteen-6',
    name: 'Don Tawan Canteen',
    thaiName: 'โรงอาหารดอนตะวัน',
    locationNote: 'Near Suraniwet Dorm 15',
    shortName: 'Don Tawan',
    tagline: 'Cozy campus cafe & made-to-order',
    imageUrl: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=600&q=80',
    lat: 14.8860,
    lng: 102.0210,
    openHours: '08:00 - 20:00',
    baseQueueMinutes: 5,
    queueLevel: 'Low',
    stalls: [],
  },
  {
    id: 'canteen-4',
    name: 'Den Thong Kwao Canteen',
    thaiName: 'โรงอาหารเด่นทองกวาว',
    locationNote: 'Opposite Academic Building 2',
    shortName: 'Den Thong Kwao',
    tagline: 'Quiet atmosphere near scientific equipment center',
    imageUrl: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=600&q=80',
    lat: 14.8745,
    lng: 102.0175,
    openHours: '08:00 - 17:00',
    baseQueueMinutes: 3,
    queueLevel: 'Low',
    stalls: [],
  },
  {
    id: 'canteen-1',
    name: 'Prao Saed Thong Canteen',
    thaiName: 'โรงอาหารพราวแสดทอง',
    locationNote: 'Lecture Building 1 (B1)',
    shortName: 'Prao Saed Thong',
    tagline: 'Hub of delicious food next to B1',
    imageUrl: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=600&q=80',
    lat: 14.8783,
    lng: 102.0195,
    openHours: '07:00 - 18:00',
    baseQueueMinutes: 4,
    queueLevel: 'Low',
    stalls: [
      {
        id: 'stall-gohub-chicken',
        canteenId: 'canteen-1',
        name: 'Go Hub Hainanese Chicken',
        thaiName: 'ข้าวมันไก่โกฮับ',
        category: 'Made-to-Order',
        imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&q=80',
        waitMinutes: 3,
        rating: 4.8,
        isOpen: true,
        fastest: true,
        menus: [
          { id: 'm-gh-1', name: 'Hainanese Steamed Chicken Rice', price: 40, prepTime: 3, desc: 'Tender chicken with fragrant ginger rice', popular: true },
          { id: 'm-gh-2', name: 'Crispy Fried Chicken Rice', price: 45, prepTime: 3, desc: 'Golden crispy chicken with sweet chili dip', popular: true },
        ],
      },
    ],
  },
  {
    id: 'canteen-2',
    name: 'Rong Tiam Canteen (B2)',
    thaiName: 'โรงอาหารอาคารเรียนรวม 2',
    locationNote: 'Lecture Building 2 (B2)',
    shortName: 'Rong Tiam B2',
    tagline: 'Favorite lunch spot for engineering students',
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=600&q=80',
    lat: 14.8768,
    lng: 102.0221,
    openHours: '07:30 - 17:30',
    baseQueueMinutes: 20,
    queueLevel: 'High',
    stalls: [
      {
        id: 'stall-engineer-tray',
        canteenId: 'canteen-2',
        name: 'Engineer Basil Tray',
        thaiName: 'กะเพราถาดเด็กวิดวะ',
        category: 'Made-to-Order',
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
        waitMinutes: 8,
        rating: 4.9,
        isOpen: true,
        fastest: false,
        menus: [
          { id: 'm-et-1', name: 'Giant Pork Basil Tray + 2 Fried Eggs', price: 50, prepTime: 6, desc: 'Huge tray portion with 2 crispy fried eggs', popular: true },
        ],
      },
    ],
  },
];

export const CAMPUS_DISTANCE_MATRIX = {
  'bld-dorm-low': {
    'canteen-5': 1, // Directly at Kasalong Canteen
    'canteen-1': 8,
    'canteen-2': 7,
    'canteen-3': 6,
    'canteen-4': 9,
    'canteen-6': 3,
  },
  'bld-b1': {
    'canteen-1': 1,
    'canteen-2': 4,
    'canteen-3': 5,
    'canteen-4': 6,
    'canteen-5': 8,
    'canteen-6': 10,
  },
  'bld-b2': {
    'canteen-1': 4,
    'canteen-2': 1,
    'canteen-3': 7,
    'canteen-4': 5,
    'canteen-5': 7,
    'canteen-6': 10,
  },
  'bld-eng1': {
    'canteen-1': 5,
    'canteen-2': 5,
    'canteen-3': 6,
    'canteen-4': 2,
    'canteen-5': 9,
    'canteen-6': 11,
  },
  'bld-eng2': {
    'canteen-1': 6,
    'canteen-2': 5,
    'canteen-3': 7,
    'canteen-4': 1,
    'canteen-5': 10,
    'canteen-6': 12,
  },
  'bld-lib': {
    'canteen-1': 3,
    'canteen-2': 5,
    'canteen-3': 3,
    'canteen-4': 5,
    'canteen-5': 7,
    'canteen-6': 8,
  },
  'bld-dorm-high': {
    'canteen-6': 1,
    'canteen-5': 3,
    'canteen-3': 8,
    'canteen-1': 10,
    'canteen-2': 9,
    'canteen-4': 11,
  },
};

// Fast-Lane Grab & Go Express Items (Empty by default)
export const INITIAL_GRAB_AND_GO_ITEMS = [];
